"""
Django settings for CRM_MongoDB project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from pymongo.mongo_client import MongoClient
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yf_=$2l-dcqkn3m(unu)rbnunn)2ap+jv6*m$*zs0+s)g(pqlo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'rest_framework',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
AUTHENTICATION_BACKENDS = ('api.backends.CaseInsensitiveModelBackend', )


CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_HEADERS = ('*')

ROOT_URLCONF = 'CRM_MongoDB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CRM_MongoDB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'prydan-crm-database',
        # 'CLIENT': {
        #    'host': 'prydan-crm-database.mongo.cosmos.azure.com',
        #    'port' : 10255,
        #    'username' : 'prydan-crm-database',
        #    'password' : 'D8hdOZp0GLu2uiK6dq0RXrR2AHVgmXWqXXnz0rxIXutyknVcvLMu2uvw9jvcVQfErtbTAl2xw8ARNI8mXBn54g==',
        # }
        # 'HOST' : 'mongodb:+srv//prydan-crm-database:D8hdOZp0GLu2uiK6dq0RXrR2AHVgmXWqXXnz0rxIXutyknVcvLMu2uvw9jvcVQfErtbTAl2xw8ARNI8mXBn54g==@prydan-crm-database.mongo.cosmos.azure.com:10255/?ssl=true&ssl_cert_reqs=CERT_NONE&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@prydan-crm-database@',
        # 'HOST' : 'prydan-crm-database.mongo.cosmos.azure.com',
        # 'PORT' : 10255,
        # 'USER' : 'prydan-crm-database',
        # 'PASSWORD' : 'D8hdOZp0GLu2uiK6dq0RXrR2AHVgmXWqXXnz0rxIXutyknVcvLMu2uvw9jvcVQfErtbTAl2xw8ARNI8mXBn54g==',
    }
}

MongoClient.HOST = 'mongodb://prydan-crm-database:D8hdOZp0GLu2uiK6dq0RXrR2AHVgmXWqXXnz0rxIXutyknVcvLMu2uvw9jvcVQfErtbTAl2xw8ARNI8mXBn54g==@prydan-crm-database.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@prydan-crm-database@'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         # 'rest_framework.authentication.BasicAuthentication',
#         # 'rest_framework.authentication.SessionAuthentication',
#         # 'rest_framework_simplejwt.authentication.JWTAuthentication',
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
#     'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
#     # 'DEFAULT_RENDERER_CLASSES': (
#     #     'rest_framework.renderers.JSONRenderer',
#     # ),
#     # 'DEFAULT_PARSER_CLASSES': (
#     #     'rest_framework.parsers.JSONParser',
#     # )
# }

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# SIMPLE_JWT = {
# 'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
# # 'REFRESH_TOKEN_LIFETIME': timedelta(seconds=2400)
# 'REFRESH_TOKEN_LIFETIME': timedelta(days=2)
# }
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Prydan CRM",
    "site_header": "Prydan CRM",
    "site_brand": "Library",

    "site_logo": "/logo.jpeg",
    "site_logo_classes": "img-circle",


    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Prydan CRM",

    "copyright": "Prydan CRM Ltd",

    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": "auth.User",

    "order_with_respect_to": ["auth", "api"],
}
# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
